### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by HoHieuLuc** [HoHieuLuc/ThucTapIVS_TMDT#47]
Yêu cầu báo cáo cho tuần 6

- đưa sản phẩm là new
- hiện tên người đăng sản phẩm trong trang chi tiết sản phẩm
- filter lọc bình luận, lọc các từ khóa bậy bạ, nhạy cảm đối với lĩnh lực hàng hóa sản phẩm bằng javascript ( Điểm cao, nếu làm thêm, không làm không có bị trừ )
- Lí do vì sao nhận ra bình luận đã đăng, làm cái thông báo nhắc nhở người dùng đã bình luận, Thiện sẽ làm front end đổi cái từ đăng bình luận sang cập nhật bình luận (khi người dùng đã có sẵn bình luận rồi)
- 100 công ty đăng lên 100 món hàng,trang chủ chật, phân trang mà :)))
- hiển thị sản phẩm theo người đăng cụ thể, có phân trang
- làm cái giao diện sản phẩm của riêng 1 người nào đó (lấy mã khách hàng :))   )

**Comment by lamminhthien-ntu** [comment]
duyệt

**Comment by HoHieuLuc** [comment]
tui nghĩ là mình chuyển mấy cái kiểu date trong csdl của mình thành datetime hết ngoại trừ ngày sinh ra để nó lưu được theo kiểu  YYYY-MM-DD hh:mm:ss, ví dụ ngày đánh giá 01/01/2021 lúc 8h12p50s, khi insert hay update thì mình chỉ việc xài hàm NOW() trong câu lệnh sql thôi, vì mình có bao giờ cần chỉnh ngày giờ tay đâu

**Comment by lamminhthien-ntu** [comment]
Hợp lý ô, lưu bằng now() đỡ mất công viết code đổi thời gian bên java.

**Comment by HoHieuLuc** [comment]
trim hết mấy cái input string, cái này để thứ 6 làm

**Comment by HoHieuLuc** [comment]
register chưa insert vô bảng thông tin liên hệ

**Comment by lamminhthien-ntu** [comment]
Ohno, tui thiếu nó, tui bổ sung ngay

**Comment by HoHieuLuc** [comment]
xem phản hồi vẫn bị lỗi ngày sửa

**Comment by HoHieuLuc** [comment]
mỗi lần gọi giỏ hàng là kiểm tra xong tự động cập nhật lại giỏ hàng nếu số lượng vượt quá luôn

**Comment by HoHieuLuc** [comment]
![keqsad](https://user-images.githubusercontent.com/62865718/150518279-dea96fb0-49a6-415c-9a5c-520892d97de3.png)

**Comment by lamminhthien-ntu** [comment]
> ![keqsad](https://user-images.githubusercontent.com/62865718/150518279-dea96fb0-49a6-415c-9a5c-520892d97de3.png)
hửm, sao con lại khóc :))
