### ISSUE TITLE
Không hiện thông báo không có loại sản phẩm này

### ISSUE THREAD

**Issue by HoHieuLuc** [HoHieuLuc/ThucTapIVS_TMDT#82]
Nhập id loại sản phẩm không tồn tại auto ra điện thoại

![image](https://user-images.githubusercontent.com/62865718/148073269-0735272c-e564-4bf9-b147-53645d20c52a.png)
![image](https://user-images.githubusercontent.com/62865718/148073133-9627d9d8-4eb7-4427-ab19-d548b27516fd.png)
![image](https://user-images.githubusercontent.com/62865718/148073158-f7c096b5-0a4c-4f10-9649-a2e9a849797f.png)

**Comment by lamminhthien-ntu** [comment]
Vậy tui sẽ sửa thành 
<h1>Trang không tồn tại</h1>
<p>Bấm vào đây để về trang chủ</p>

**Comment by lamminhthien-ntu** [comment]
Mà có cách nào tự chuyển trang về trang chủ
xong hiện thông báo <p>Trang bạn truy cập không hợp lệ </p>
không ô, vì mình redirect sang trang khác ấy
